- name: Run PowerShell Script to Deploy Splunk Forwarder to WIN11A.condef.local
  ansible.windows.win_powershell:
    script: |
      Write-Host "Creating Directory..."

      New-Item -Path C:\ -Name SplunkFiles -ItemType Directory

      Write-Host "Downloading Splunk Forwarder..."

      Invoke-WebRequest -UseBasicParsing "https://download.splunk.com/products/universalforwarder/releases/10.0.1/windows/splunkforwarder-10.0.1-c486717c322b-windows-x64.msi" -OutFile C:\SplunkFiles\forwarder.msi

      Write-Host "Downloading Windows TA App..."

      Invoke-WebRequest -UseBasicParsing "https://github.com/Antonlovesdnb/ConstructingDefenseLab/raw/refs/heads/main/files/splunkappswin11a.zip" -OutFile C:\SplunkFiles\splunkappswin11a.zip

      Write-Host "Installing Forwarder..."

      Start-Process msiexec.exe -ArgumentList '/I C:\SplunkFiles\forwarder.msi AGREETOLICENSE=Yes SPLUNKUSERNAME=Condef SPlUNKPASSWORD=Temp1234!! RECEIVING_INDEXER="DC:9997" /quiet' -PassThru -Wait

      Write-Host "Installing Windows TA App.."

      Expand-Archive -LiteralPath C:\SplunkFiles\splunkappswin11a.zip -DestinationPath 'C:\Program Files\SplunkUniversalForwarder\etc\apps'

      Start-Process sc.exe -ArgumentList 'config "splunkforwarder" obj="Localsystem"'

      Write-Host "Restarting Splunk Forwarder"

      Restart-Service SplunkForwarder

      Write-Host "Disabling Firewall"

      Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
